/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esanteInterface;
import java.sql.*;
import static esanteInterface.MySQLConnection.*;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ideap
 */
public class FeedbackPage extends javax.swing.JFrame {

    /**
     * Creates new form FeedbackPage
     */
    public FeedbackPage() {
        initComponents();
    }
    
public void insertFeedback() {
    String query = "INSERT INTO feedback VALUES (?, ?, ?, ?, ?, ?)";
    service1.setActionCommand("1");
    service2.setActionCommand("2");
    service3.setActionCommand("3");
    service4.setActionCommand("4");
    service5.setActionCommand("5");

    ponct1.setActionCommand("1");
    ponct2.setActionCommand("2");
    ponct3.setActionCommand("3");
    ponct4.setActionCommand("4");
    ponct5.setActionCommand("5");

    traitem1.setActionCommand("1");
    traitem2.setActionCommand("2");
    traitem3.setActionCommand("3");
    traitem4.setActionCommand("4");
    traitem5.setActionCommand("5");

    try (Connection conn = getConnection();
         PreparedStatement pstmt = conn.prepareStatement(query)) {

        pstmt.setInt(1, Integer.parseInt(consultIDField.getText()));
        pstmt.setString(2, commentField.getText());
        pstmt.setInt(3, Integer.parseInt(serviceRating.getSelection().getActionCommand()));
        pstmt.setInt(4, Integer.parseInt(ponctRating.getSelection().getActionCommand()));
        pstmt.setInt(5, Integer.parseInt(traitementRating.getSelection().getActionCommand()));
        pstmt.setInt(6, Integer.parseInt(consultIDField.getText()));

        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Record inserted successfully!");
    } catch (SQLIntegrityConstraintViolationException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Feedback for the same consultID already exists in the database.");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred while inserting the feedback record.");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serviceRating = new javax.swing.ButtonGroup();
        ponctRating = new javax.swing.ButtonGroup();
        traitementRating = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        commentField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        service1 = new javax.swing.JRadioButton();
        service2 = new javax.swing.JRadioButton();
        service3 = new javax.swing.JRadioButton();
        service4 = new javax.swing.JRadioButton();
        service5 = new javax.swing.JRadioButton();
        ponct4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        ponct5 = new javax.swing.JRadioButton();
        ponct1 = new javax.swing.JRadioButton();
        ponct2 = new javax.swing.JRadioButton();
        ponct3 = new javax.swing.JRadioButton();
        traitem4 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        traitem5 = new javax.swing.JRadioButton();
        traitem1 = new javax.swing.JRadioButton();
        traitem2 = new javax.swing.JRadioButton();
        traitem3 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        confirmFeedback = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        consultIDField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Donner Votre Avis:");

        commentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setText("* Consultation Id:");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("* Service /5: ");

        serviceRating.add(service1);
        service1.setText("1");
        service1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service1ActionPerformed(evt);
            }
        });

        serviceRating.add(service2);
        service2.setText("2");
        service2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service2ActionPerformed(evt);
            }
        });

        serviceRating.add(service3);
        service3.setText("3");
        service3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service3ActionPerformed(evt);
            }
        });

        serviceRating.add(service4);
        service4.setText("4");
        service4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service4ActionPerformed(evt);
            }
        });

        serviceRating.add(service5);
        service5.setText("5");
        service5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service5ActionPerformed(evt);
            }
        });

        ponctRating.add(ponct4);
        ponct4.setText("4");
        ponct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponct4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel10.setText("* Ponctualité /5:");

        ponctRating.add(ponct5);
        ponct5.setText("5");
        ponct5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponct5ActionPerformed(evt);
            }
        });

        ponctRating.add(ponct1);
        ponct1.setText("1");
        ponct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponct1ActionPerformed(evt);
            }
        });

        ponctRating.add(ponct2);
        ponct2.setText("2");
        ponct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponct2ActionPerformed(evt);
            }
        });

        ponctRating.add(ponct3);
        ponct3.setText("3");
        ponct3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponct3ActionPerformed(evt);
            }
        });

        traitementRating.add(traitem4);
        traitem4.setText("4");
        traitem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traitem4ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel16.setText("* Traitement /5:");

        traitementRating.add(traitem5);
        traitem5.setText("5");
        traitem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traitem5ActionPerformed(evt);
            }
        });

        traitementRating.add(traitem1);
        traitem1.setText("1");
        traitem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traitem1ActionPerformed(evt);
            }
        });

        traitementRating.add(traitem2);
        traitem2.setText("2");
        traitem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traitem2ActionPerformed(evt);
            }
        });

        traitementRating.add(traitem3);
        traitem3.setText("3");
        traitem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traitem3ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel21.setText("Commentaire:");

        confirmFeedback.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        confirmFeedback.setText("CONFIRMER");
        confirmFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmFeedbackActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButton2.setText("RETOUR");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67)
                            .addComponent(traitem1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(traitem2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(traitem3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(traitem4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(traitem5))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67)
                            .addComponent(ponct1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ponct2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ponct3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ponct4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ponct5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(service1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(service2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(service3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(service4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(service5))
                    .addComponent(confirmFeedback, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(commentField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(consultIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(service1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(service2)
                    .addComponent(service3)
                    .addComponent(service4)
                    .addComponent(service5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ponct5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ponct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ponct2)
                    .addComponent(ponct3)
                    .addComponent(ponct4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traitem2)
                    .addComponent(traitem3)
                    .addComponent(traitem4)
                    .addComponent(traitem5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(traitem1)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmFeedback)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void commentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentFieldActionPerformed

    private void service1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service1ActionPerformed

    private void service2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service2ActionPerformed

    private void service3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service3ActionPerformed

    private void service4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service4ActionPerformed

    private void service5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service5ActionPerformed

    private void ponct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponct4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponct4ActionPerformed

    private void ponct5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponct5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponct5ActionPerformed

    private void ponct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponct1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponct1ActionPerformed

    private void ponct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponct2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponct2ActionPerformed

    private void ponct3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponct3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponct3ActionPerformed

    private void traitem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traitem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traitem4ActionPerformed

    private void traitem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traitem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traitem5ActionPerformed

    private void traitem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traitem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traitem1ActionPerformed

    private void traitem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traitem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traitem2ActionPerformed

    private void traitem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traitem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traitem3ActionPerformed

    private void confirmFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmFeedbackActionPerformed
        if (consultIDField.getText().equals("") || serviceRating.getSelection()==null || ponctRating.getSelection()==null || traitementRating.getSelection()==null) {
            JOptionPane.showMessageDialog(this, "Veuillez Remplir Tous Les Champs Obligatoires SVP!");
        }
        else {
           insertFeedback(); 
        }
    }//GEN-LAST:event_confirmFeedbackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginP blogin= new LoginP();
        this.setVisible(false);
        blogin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedbackPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField commentField;
    private javax.swing.JButton confirmFeedback;
    private javax.swing.JTextField consultIDField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton ponct1;
    private javax.swing.JRadioButton ponct2;
    private javax.swing.JRadioButton ponct3;
    private javax.swing.JRadioButton ponct4;
    private javax.swing.JRadioButton ponct5;
    private javax.swing.ButtonGroup ponctRating;
    private javax.swing.JRadioButton service1;
    private javax.swing.JRadioButton service2;
    private javax.swing.JRadioButton service3;
    private javax.swing.JRadioButton service4;
    private javax.swing.JRadioButton service5;
    private javax.swing.ButtonGroup serviceRating;
    private javax.swing.JRadioButton traitem1;
    private javax.swing.JRadioButton traitem2;
    private javax.swing.JRadioButton traitem3;
    private javax.swing.JRadioButton traitem4;
    private javax.swing.JRadioButton traitem5;
    private javax.swing.ButtonGroup traitementRating;
    // End of variables declaration//GEN-END:variables
}
