
package esanteInterface;
import model.*;
import java.sql.*;
import javax.swing.JOptionPane;


public class LoginP extends javax.swing.JFrame {

    
    public LoginP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginUSR = new javax.swing.JTextField();
        loginPW = new javax.swing.JPasswordField();
        confirmerLogin = new javax.swing.JButton();
        recoverPW = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        laisserAvis = new javax.swing.JButton();
        recoverPW1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setText("Mot de Passe");

        loginUSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUSRActionPerformed(evt);
            }
        });

        loginPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginPWKeyPressed(evt);
            }
        });

        confirmerLogin.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        confirmerLogin.setText("ACCEDER");
        confirmerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerLoginActionPerformed(evt);
            }
        });
        confirmerLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmerLoginKeyPressed(evt);
            }
        });

        recoverPW.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        recoverPW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recoverPW.setText("Vous n'avez pas de compte ?");
        recoverPW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recoverPWMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bienvenue a eSanté !");

        laisserAvis.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        laisserAvis.setText("LAISSER VOTRE AVIS");
        laisserAvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laisserAvisActionPerformed(evt);
            }
        });

        recoverPW1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        recoverPW1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recoverPW1.setText("Mot de Passe Oublié ?");
        recoverPW1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recoverPW1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(recoverPW, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recoverPW1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(loginUSR, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(loginPW, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(confirmerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laisserAvis, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loginUSR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loginPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(confirmerLogin)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recoverPW)
                    .addComponent(recoverPW1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(laisserAvis)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmerLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmerLoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmerLoginKeyPressed

    private void confirmerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerLoginActionPerformed
        if (loginUSR.getText().equals(Admin.getuserName()) && loginPW.getText().equals(Admin.getpW())) {
            HomePageAdmin hpadmin= new HomePageAdmin();
            this.setVisible(false);
            hpadmin.setVisible(true);
        }
        else {
            try {
                Connection conn = (Connection) MySQLConnection.getConnection();
                String query="SELECT userName,userPW From Employee where userName=? and userPW=?;";
                PreparedStatement pst=conn.prepareStatement(query);
                pst.setString(1,loginUSR.getText());
                pst.setString(2,loginPW.getText());
                ResultSet rs=pst.executeQuery();
                if (rs.next()){
                    ESante.user=loginUSR.getText();
                    ESante.pw=loginPW.getText();
                    String query1="SELECT userName,userPW From Medcin, Employee where Employee.userName=? and Employee.userPW=? and Medcin.codeEmployee=Employee.codeEmployee;";
                    PreparedStatement pst1=conn.prepareStatement(query1);
                    pst1.setString(1,loginUSR.getText());
                    pst1.setString(2,loginPW.getText());
                    ResultSet rs1=pst1.executeQuery();
                    if (rs1.next()){
                        HomePageMed hpmed= new HomePageMed();
                        this.setVisible(false);
                        hpmed.setVisible(true);
                        ESante.consul="ConsultationMed";
                    }
                    else {
                        HomePageParamed hparamed= new HomePageParamed();
                        this.setVisible(false);
                        hparamed.setVisible(true);
                        ESante.consul="ConsultationParamed";
                    }
                }
                else {
                    JOptionPane.showMessageDialog(null,"User AND/OR PW Incorrect");
                }
                MySQLConnection.closeConnection();
            }
            catch (SQLException ex) {

            }

        }
    }//GEN-LAST:event_confirmerLoginActionPerformed

    private void loginUSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUSRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUSRActionPerformed

    private void recoverPWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recoverPWMouseClicked
        RegisterPage registerpage= new RegisterPage();
        this.setVisible(false);
        registerpage.setVisible(true);
    }//GEN-LAST:event_recoverPWMouseClicked

    private void laisserAvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laisserAvisActionPerformed
        FeedbackPage avispage= new FeedbackPage();
        this.setVisible(false);
        avispage.setVisible(true);
    }//GEN-LAST:event_laisserAvisActionPerformed

    private void recoverPW1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recoverPW1MouseClicked
        RecoverPW recoverpage= new RecoverPW();
        this.setVisible(false);
        recoverpage.setVisible(true);
    }//GEN-LAST:event_recoverPW1MouseClicked

    private void loginPWKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginPWKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPWKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmerLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton laisserAvis;
    private javax.swing.JPasswordField loginPW;
    private javax.swing.JTextField loginUSR;
    private javax.swing.JLabel recoverPW;
    private javax.swing.JLabel recoverPW1;
    // End of variables declaration//GEN-END:variables
}
